seed: 42
kfold:  5
model:
  num_classes:  6
  num_channels: 15
  with_dropout: True
  dropout: 0.5
data:
  dataset:
    sample_num: 3000
    max_num_classes: 6
    transform : True
  dataloader:
    batch_size: 128
    num_workers: 8
train:
  epoch: 200        
  accelerator: "gpu"
  devices:  1
  precision: "16-mixed"
  ddp: False
  accumulate_grad_batches: 1
  log_every_n_steps: 1
  optimizer:
    learning_rate: 1e-3
    weight_decay: 1e-7
  scheduler:
    step_size: 10
    gamma: 0.5